// This file is auto-generated by scripts/generate-build-info.js during Netlify deployment
// Do not edit manually - changes will be overwritten on next build

export const environment = {
  production: true,
  googleClientId: '324607101110-jm62j15nm96l1pn0u4dtapr0iie6u5ei.apps.googleusercontent.com',
  
  // Build metadata (auto-generated from Netlify environment)
  build: {
    buildId: 'local-dev',
    deployId: 'local',
    shortDeployId: 'local',
    commitRef: 'unknown',
    shortCommit: 'unknown',
    context: 'development',
    deployTime: '2025-12-23T12:50:39.313Z',
    deployUrl: 'http://localhost:4200',
    version: '0.0.0'
  }
};
