// This file is auto-generated by scripts/generate-build-info.js during Netlify deployment
// Do not edit manually - changes will be overwritten on next build

export const environment = {
  production: true,
  googleClientId: '415057442876-1lpa3bgneif4l2gnd6g1anml9o49hl0l.apps.googleusercontent.com',
  
  // Build metadata
  build: {
    version: '1.0.0',
    deployDate: '2025-12-26T09:22:49.326Z',
    isProduction: false
  }
};
